/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    comments: Comment;
    islands: Island;
    places: Place;
    businesses: Business;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    islands: IslandsSelect<false> | IslandsSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'dv' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    title?: string | null;
    type:
      | 'none'
      | 'landing'
      | 'highImpact'
      | 'mediumImpact'
      | 'lowImpact'
      | 'heroCarousel'
      | 'adventure'
      | 'cosmetic'
      | 'eventDetails';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    posts?: (string | Post)[] | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * For Event Details, this is the large center image in the gallery mosaic.
     */
    media?: (string | null) | Media;
    /**
     * Small pill label, e.g. "East Java's Natural Wonder" or "Top Rated" (Event Details)
     */
    badge?: string | null;
    /**
     * Nav links shown over the hero image
     */
    navItems?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Stacked avatar images for the "X People Joined" badge
     */
    avatars?:
      | {
          image: string | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * e.g. "50+"
     */
    joinedCount?: string | null;
    /**
     * e.g. "People Joined"
     */
    joinedLabel?: string | null;
    description?: string | null;
    /**
     * Phone number shown in the top nav, e.g. "+1 (555) 123-4567"
     */
    phone?: string | null;
    /**
     * e.g. "Dr. Isabella Cruz, MD"
     */
    doctorName?: string | null;
    /**
     * e.g. "Aesthetic Medicine & Dermatological Care"
     */
    doctorTitle?: string | null;
    /**
     * The larger, first card in the gallery strip
     */
    featuredImage?: (string | null) | Media;
    featuredTitle?: string | null;
    featuredDescription?: string | null;
    /**
     * The smaller image cards in the gallery strip. For Event Details, the first 2 form the left column and the last 2 form the right column around the center image.
     */
    galleryImages?:
      | {
          image: string | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Breadcrumb label, e.g. "Classic"
     */
    category?: string | null;
    /**
     * e.g. "AJJR"
     */
    tripCode?: string | null;
    /**
     * Row of icon stats under the description, e.g. Duration, Group Size, Physical Rating, Accommodation
     */
    quickStats?:
      | {
          /**
           * Lucide icon name, e.g. Clock, Users, Activity, Building2
           */
          icon?: string | null;
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The sticky booking card shown alongside the gallery
     */
    priceBox?: {
      /**
       * e.g. "9 days"
       */
      durationLabel?: string | null;
      /**
       * e.g. "Osaka to Tokyo"
       */
      route?: string | null;
      price: number;
      originalPrice?: number | null;
      currency?: string | null;
      /**
       * e.g. "Jul 31 2026"
       */
      validOn?: string | null;
      /**
       * Out of 5
       */
      rating?: number | null;
      reviewCount?: number | null;
      /**
       * Small icon row, e.g. Flight Included, Hotels Comfortable Stay, Tours Expert Guides
       */
      includes?:
        | {
            /**
             * Lucide icon name, e.g. Plane, Hotel, MapPin
             */
            icon?: string | null;
            label: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | BlogArchiveBlock
    | LatestNewsV2Block
    | FormBlock
    | {
        badge?: string | null;
        /**
         * e.g. "Frequently Asked"
         */
        title?: string | null;
        /**
         * Rendered in italic serif on its own line, e.g. "Questions"
         */
        titleAccent?: string | null;
        /**
         * e.g. "hello@vistaire.com"
         */
        email?: string | null;
        ctaLabel?: string | null;
        /**
         * e.g. "mailto:hello@vistaire.com"
         */
        ctaLink?: string | null;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        /**
         * Photo shown alongside the FAQ list
         */
        image?: (string | null) | Media;
        /**
         * e.g. "@skyline.villas"
         */
        imageCaption?: string | null;
        /**
         * Optional cursive signature shown below the section, e.g. "crafted setared"
         */
        signatureName?: string | null;
        /**
         * e.g. "for real estate"
         */
        signatureTagline?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | QuickFactsBlock
    | GalleryBlock
    | PlacesGridBlock
    | BusinessDirectoryBlock
    | TimelineBlock
    | ContactInfoBlock
    | TestimonialsBlock
    | WhyUsBlock
    | StatsBlock
    | DestinationsBlock
    | EventTimelineBlock
    | WhatsIncludedBlock
    | RecommendedToursBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  island?: (string | null) | Island;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Short description of this category
   */
  description?: string | null;
  /**
   * Icon name (e.g., MapPin, Camera, Waves, Fish, Fork)
   */
  icon?: string | null;
  /**
   * Hex color code for category (e.g., #FF6B6B)
   */
  color?: string | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islands".
 */
export interface Island {
  id: string;
  /**
   * Island or atoll name
   */
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Brief description of the island
   */
  description?: string | null;
  /**
   * Featured image of the island
   */
  image?: (string | null) | Media;
  location?: {
    latitude?: number | null;
    longitude?: number | null;
    /**
     * Atoll name (e.g., Malé City, Thiladhummati, Ari)
     */
    atoll?: string | null;
  };
  /**
   * Main attractions and activities on this island
   */
  attractions?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Best season and weather information
   */
  bestTimeToVisit?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  position?: ('default' | 'fullscreen') | null;
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogArchiveBlock".
 */
export interface BlogArchiveBlock {
  /**
   * Small pill label shown above the section, e.g. "Latest News".
   */
  badge?: string | null;
  /**
   * Short line shown under the badge.
   */
  subtitle?: string | null;
  /**
   * Large heading shown on the right, e.g. "What's Happening Across the Islands?".
   */
  heading?: string | null;
  /**
   * The most recent post is featured large; the next two appear as thumbnails; the fourth is shown as a highlighted excerpt.
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestNewsV2Block".
 */
export interface LatestNewsV2Block {
  /**
   * Large heading shown on the left, e.g. "Latest News".
   */
  heading?: string | null;
  /**
   * Short paragraph shown under the heading.
   */
  subtitle?: string | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    label: string;
  };
  /**
   * How many recent posts to list on the right.
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestNewsV2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickFactsBlock".
 */
export interface QuickFactsBlock {
  title?: string | null;
  layout?: ('stats' | 'mosaic') | null;
  /**
   * Stats layout only. Intro paragraph(s) shown next to the stats, e.g. an "About Us" blurb.
   */
  description?: string | null;
  /**
   * Stats layout only. Optional call-to-action shown under the description.
   */
  button?: {
    label?: string | null;
    url?: string | null;
  };
  /**
   * Stats layout only. Large background photo of the collage.
   */
  image1?: (string | null) | Media;
  /**
   * Stats layout only. Smaller rotated photo overlapping the first.
   */
  image2?: (string | null) | Media;
  /**
   * Stats layout e.g. Population, Size, Atoll, Distance from Malé, Ferry Duration, Speedboat Duration, Airport, Time Zone, Language, Currency, Island Code. Mosaic layout e.g. Spa, Explore, Native Cuisine, Weddings, Luxury Resorts.
   */
  facts: {
    /**
     * Stats layout only. Lucide icon name, e.g. Users, MapPin, Ship, Plane, Globe, Clock
     */
    icon?: string | null;
    /**
     * Stats layout: the value's caption. Mosaic layout: the tile heading, e.g. "SPA".
     */
    label?: string | null;
    /**
     * Stats layout only, e.g. "12,000".
     */
    value?: string | null;
    /**
     * Mosaic layout only. Short paragraph shown under the tile heading.
     */
    description?: string | null;
    /**
     * Mosaic layout only.
     */
    variant?: ('image' | 'color') | null;
    /**
     * Mosaic layout, photo tile only.
     */
    image?: (string | null) | Media;
    /**
     * Mosaic layout, color tile only.
     */
    color?: ('blue' | 'white') | null;
    /**
     * Mosaic layout only. Controls how many grid cells this tile fills.
     */
    span?: ('normal' | 'wide' | 'tall') | null;
    /**
     * Mosaic layout only. Optional call-to-action shown on the tile.
     */
    button?: {
      label?: string | null;
      url?: string | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'quickFacts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * Small label above the title, e.g. "GALLERY". Only used by the Coverflow layout.
   */
  eyebrow?: string | null;
  title?: string | null;
  /**
   * Short subheading below the title. Only used by the Coverflow layout.
   */
  description?: string | null;
  layout?: ('grid' | 'masonry' | 'slider' | 'coverflow') | null;
  /**
   * Only used by the Coverflow layout.
   */
  viewMoreLabel?: string | null;
  /**
   * Only used by the Coverflow layout.
   */
  viewMoreUrl?: string | null;
  images: {
    image: string | Media;
    caption?: string | null;
    /**
     * Filter pill label for this image, e.g. "Italy", "Dubai". Only used by the Coverflow layout.
     */
    location?: string | null;
    /**
     * Shows a play icon on the card. Only used by the Coverflow layout.
     */
    isVideo?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlacesGridBlock".
 */
export interface PlacesGridBlock {
  title?: string | null;
  type: 'thingsToDo' | 'placesToVisit' | 'beach';
  /**
   * Leave empty to show places from all islands
   */
  island?: (string | null) | Island;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'placesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BusinessDirectoryBlock".
 */
export interface BusinessDirectoryBlock {
  title?: string | null;
  category?: ('all' | 'restaurant' | 'shop' | 'accommodation' | 'service') | null;
  /**
   * Leave empty to show businesses from all islands
   */
  island?: (string | null) | Island;
  featuredOnly?: boolean | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'businessDirectory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  title?: string | null;
  /**
   * e.g. Founded, important events, development milestones, infrastructure
   */
  events: {
    year: string;
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock".
 */
export interface ContactInfoBlock {
  title?: string | null;
  description?: string | null;
  /**
   * Large background photo
   */
  image1?: (string | null) | Media;
  /**
   * Smaller overlapping photo
   */
  image2?: (string | null) | Media;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Google Maps embed URL
   */
  mapEmbedUrl?: string | null;
  emergencyContacts?:
    | {
        /**
         * e.g. Hospital, Police, Fire, Council, Harbor Master
         */
        label: string;
        icon?: ('shield' | 'flame' | 'lifeBuoy' | 'cross' | 'phone') | null;
        phone: string;
        id?: string | null;
      }[]
    | null;
  emergencyNoteTitle?: string | null;
  emergencyNoteDescription?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  title?: string | null;
  items: {
    quote: string;
    name: string;
    /**
     * e.g. Visitor, Resident
     */
    role?: string | null;
    photo?: (string | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlock".
 */
export interface WhyUsBlock {
  /**
   * e.g. "Why Aviatour"
   */
  title?: string | null;
  items: {
    image: string | Media;
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  /**
   * e.g. "Discover Your Perfect Place"
   */
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaLink?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whyUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * e.g. "Your Trusted Partner In Seamless Travel"
   */
  title?: string | null;
  description?: string | null;
  image: string | Media;
  stats: {
    /**
     * e.g. "300+"
     */
    number: string;
    /**
     * e.g. "Trips expertly managed"
     */
    label: string;
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
      label: string;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DestinationsBlock".
 */
export interface DestinationsBlock {
  destinations: {
    image: string | Media;
    title: string;
    subtitle?: string | null;
    /**
     * Optional URL this destination links to
     */
    link?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'destinations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventTimelineBlock".
 */
export interface EventTimelineBlock {
  /**
   * e.g. "Itinerary"
   */
  title?: string | null;
  items: {
    /**
     * e.g. "Day 1" or "Day 4 - 5"
     */
    dayLabel: string;
    title: string;
    description?: string | null;
    images?: (string | Media)[] | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventTimeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhatsIncludedBlock".
 */
export interface WhatsIncludedBlock {
  title?: string | null;
  /**
   * e.g. "Japan Rail (JR) pass for 7 days", "8 nights hotel accommodation"
   */
  items: {
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'whatsIncluded';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecommendedToursBlock".
 */
export interface RecommendedToursBlock {
  title?: string | null;
  tours: {
    image: string | Media;
    /**
     * e.g. "ON SALE"
     */
    badge?: string | null;
    /**
     * e.g. "18-30s"
     */
    ageRange?: string | null;
    title: string;
    /**
     * e.g. "20 days"
     */
    durationLabel?: string | null;
    /**
     * e.g. "Nairobi to Victoria Falls"
     */
    route?: string | null;
    price: number;
    originalPrice?: number | null;
    currency?: string | null;
    /**
     * e.g. "Departs on Oct 05, 2026"
     */
    departsOn?: string | null;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    buttonLabel?: string | null;
    /**
     * URL this tour card links to
     */
    link?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'recommendedTours';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  post: string | Post;
  authorName: string;
  comment: string;
  /**
   * Uncheck to hide this comment from the public without deleting it.
   */
  approved?: boolean | null;
  /**
   * Honeypot field — left blank by real visitors, hidden from the public form.
   */
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: string;
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  type: 'thingsToDo' | 'placesToVisit' | 'beach';
  island?: (string | null) | Island;
  image?: (string | null) | Media;
  description?: string | null;
  location?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  openingHours?: string | null;
  /**
   * e.g. Swimming, Sunset, Family Friendly, Snorkeling, Drone Photos
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: string;
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  category: 'restaurant' | 'shop' | 'accommodation' | 'service';
  island?: (string | null) | Island;
  /**
   * Specific business type shown on the card, e.g. "Co-Working", "Hotel", "Shopping Mall", "Cinema", "Spa Beauty Parlour", "Cafe". Falls back to the category above if left blank.
   */
  typeLabel?: string | null;
  image?: (string | null) | Media;
  description?: string | null;
  phone?: string | null;
  address?: string | null;
  hours?: string | null;
  rating?: number | null;
  /**
   * Number of reviews behind the rating, e.g. 250
   */
  reviewCount?: number | null;
  openStatus?: ('open' | 'closed') | null;
  /**
   * Show in the Featured Business spotlight
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null)
    | ({
        relationTo: 'islands';
        value: string | Island;
      } | null)
    | ({
        relationTo: 'places';
        value: string | Place;
      } | null)
    | ({
        relationTo: 'businesses';
        value: string | Business;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        title?: T;
        type?: T;
        richText?: T;
        posts?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        badge?: T;
        navItems?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        avatars?:
          | T
          | {
              image?: T;
              id?: T;
            };
        joinedCount?: T;
        joinedLabel?: T;
        description?: T;
        phone?: T;
        doctorName?: T;
        doctorTitle?: T;
        featuredImage?: T;
        featuredTitle?: T;
        featuredDescription?: T;
        galleryImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        category?: T;
        tripCode?: T;
        quickStats?:
          | T
          | {
              icon?: T;
              label?: T;
              value?: T;
              id?: T;
            };
        priceBox?:
          | T
          | {
              durationLabel?: T;
              route?: T;
              price?: T;
              originalPrice?: T;
              currency?: T;
              validOn?: T;
              rating?: T;
              reviewCount?: T;
              includes?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    id?: T;
                  };
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        blogArchive?: T | BlogArchiveBlockSelect<T>;
        latestNewsV2?: T | LatestNewsV2BlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        faq?:
          | T
          | {
              badge?: T;
              title?: T;
              titleAccent?: T;
              email?: T;
              ctaLabel?: T;
              ctaLink?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              image?: T;
              imageCaption?: T;
              signatureName?: T;
              signatureTagline?: T;
              id?: T;
              blockName?: T;
            };
        quickFacts?: T | QuickFactsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        placesGrid?: T | PlacesGridBlockSelect<T>;
        businessDirectory?: T | BusinessDirectoryBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        destinations?: T | DestinationsBlockSelect<T>;
        eventTimeline?: T | EventTimelineBlockSelect<T>;
        whatsIncluded?: T | WhatsIncludedBlockSelect<T>;
        recommendedTours?: T | RecommendedToursBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  position?: T;
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogArchiveBlock_select".
 */
export interface BlogArchiveBlockSelect<T extends boolean = true> {
  badge?: T;
  subtitle?: T;
  heading?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestNewsV2Block_select".
 */
export interface LatestNewsV2BlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickFactsBlock_select".
 */
export interface QuickFactsBlockSelect<T extends boolean = true> {
  title?: T;
  layout?: T;
  description?: T;
  button?:
    | T
    | {
        label?: T;
        url?: T;
      };
  image1?: T;
  image2?: T;
  facts?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        description?: T;
        variant?: T;
        image?: T;
        color?: T;
        span?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  layout?: T;
  viewMoreLabel?: T;
  viewMoreUrl?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        location?: T;
        isVideo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlacesGridBlock_select".
 */
export interface PlacesGridBlockSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  island?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BusinessDirectoryBlock_select".
 */
export interface BusinessDirectoryBlockSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  island?: T;
  featuredOnly?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  title?: T;
  events?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock_select".
 */
export interface ContactInfoBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image1?: T;
  image2?: T;
  address?: T;
  phone?: T;
  email?: T;
  mapEmbedUrl?: T;
  emergencyContacts?:
    | T
    | {
        label?: T;
        icon?: T;
        phone?: T;
        id?: T;
      };
  emergencyNoteTitle?: T;
  emergencyNoteDescription?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlock_select".
 */
export interface WhyUsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaDescription?: T;
  ctaLink?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DestinationsBlock_select".
 */
export interface DestinationsBlockSelect<T extends boolean = true> {
  destinations?:
    | T
    | {
        image?: T;
        title?: T;
        subtitle?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventTimelineBlock_select".
 */
export interface EventTimelineBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        dayLabel?: T;
        title?: T;
        description?: T;
        images?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhatsIncludedBlock_select".
 */
export interface WhatsIncludedBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecommendedToursBlock_select".
 */
export interface RecommendedToursBlockSelect<T extends boolean = true> {
  title?: T;
  tours?:
    | T
    | {
        image?: T;
        badge?: T;
        ageRange?: T;
        title?: T;
        durationLabel?: T;
        route?: T;
        price?: T;
        originalPrice?: T;
        currency?: T;
        departsOn?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        buttonLabel?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  island?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  description?: T;
  icon?: T;
  color?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  authorName?: T;
  comment?: T;
  approved?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islands_select".
 */
export interface IslandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLock?: T;
  description?: T;
  image?: T;
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        atoll?: T;
      };
  attractions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  bestTimeToVisit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLock?: T;
  type?: T;
  island?: T;
  image?: T;
  description?: T;
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  openingHours?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLock?: T;
  category?: T;
  island?: T;
  typeLabel?: T;
  image?: T;
  description?: T;
  phone?: T;
  address?: T;
  hours?: T;
  rating?: T;
  reviewCount?: T;
  openStatus?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  ctaButton: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  /**
   * e.g. "Do you have more questions? Send us an email!"
   */
  contactPrompt?: string | null;
  contactEmail?: string | null;
  address?: string | null;
  phone?: string | null;
  /**
   * e.g. "Questions and suggestions"
   */
  phoneNote?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  navColumnTitle?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  privacyPolicyLabel?: string | null;
  privacyPolicyUrl?: string | null;
  creditText?: string | null;
  creditUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  ctaHeading?: T;
  ctaDescription?: T;
  ctaButton?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  contactPrompt?: T;
  contactEmail?: T;
  address?: T;
  phone?: T;
  phoneNote?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  navColumnTitle?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  privacyPolicyLabel?: T;
  privacyPolicyUrl?: T;
  creditText?: T;
  creditUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success' | 'promo';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Photo shown on the right side of the diagonal split
   */
  backgroundImage?: (string | null) | Media;
  logo?: (string | null) | Media;
  /**
   * e.g. "Build a Wildly Successful Life Abroad!"
   */
  tagline?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}